version: "3.8"

services:

  db:
    image: mysql:8.0
    container_name: db_cont
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - notes-app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  django:
    build: .
    container_name: django_cont
    command: sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - notes-app

  nginx:
    build: ./nginx
    container_name: nginx_cont
    restart: always
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - notes-app

networks:
  notes-app:

volumes:
  mysql_data:
